### ISSUE TITLE
jshint is reporting 2 errors

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/ohana-web-search#716]
When I run `bin/rake jshint`, I get the following errors:
```
app/assets/javascripts/result/result-map.js: line 8, col 10, This function has too many statements. (47)
app/assets/javascripts/search/filter/search-filters.js: line 8, col 27, 'alerts' is defined but never used.
```
Can they be fixed or ignored if false positives?

**Comment by anselmbradford** [comment]
Fixed in https://github.com/codeforamerica/ohana-web-search/pull/727 and https://github.com/codeforamerica/ohana-web-search/pull/728
