### ISSUE TITLE
Upgrade to Rails 4.2

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/ohana-web-search#733]
Rails has a newer version available.

**Comment by monfresh** [comment]
This should be considered low priority at the moment, compared to other open issues. There is no pressing need to upgrade Rails. There are many changes in 4.2, and it's most likely not just a matter of running `bundle update rails`. Existing gems also have to be checked for compatibility with 4.2.

**Comment by monfresh** [comment]
Closed with #794.
