### ISSUE TITLE
Update mail gem?

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-web-search#742]
I got this email from Heroku for an instance of this project I'm running:

> You are receiving this notification because you have at least one app running a version of the Mail gem with a known memory regression. Upgrading can reduce memory footprint in a basic application by up to 36%.

> http://www.schneems.com/2014/11/07/i-ram-what-i-ram.html

> To fix, please upgrade to mail 2.6.3 above.

Would it make sense to update the mail gem version to resolve it?

**Comment by monfresh** [comment]
If you look at the [Gemfile.lock](https://github.com/codeforamerica/ohana-web-search/blob/master/Gemfile.lock#L138), you'll notice that the mail gem (which gets installed automatically by Rails) is already at version 2.6.3, which is the [latest version](https://rubygems.org/gems/mail).

I would suggest contacting Heroku and asking them why they think you have the wrong version, unless you actually do have an older version in your instance.
