### ISSUE TITLE
Switch to ESLint

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/ohana-web-search#807]
ESLint is much more powerful than JSHint and now there's a gem for it in rails finally at https://github.com/appfolio/eslint-rails ... let's switch to that (not necessary that gem, but to ESLint).

**Comment by monfresh** [comment]
💯 . The jshint gem depends on therubyracer, which in turn depends on libv8, which is failing to install on Ruby 2.3.1, so I can't upgrade this repo to 2.3.1. I would recommend using Code Climate's new engines platform to run all our static analysis. I will work on this soon.
