### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/ohana-web-search#811]
I'm posting this in case anyone has come across the same and can suggest a way to resolve. I'm guessing it might be something about my configuration, but the error below appears after cloning a fresh copy of the project  and running `rake requirejs:precompile:all RAILS_ENV=development RAILS_GROUPS=assets`. Any thoughts much appreciated.

```
** Execute requirejs:precompile:prepare_source
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/pmackay/.rvm/gems/ruby-2.2.1@ohana-web-search/gems/requirejs-rails-0.9.6/lib/tasks/requirejs-rails_tasks.rake:101:in `block (3 levels) in <top (required)>'
```

**Comment by md5** [comment]
I ran into this issue as well. Here's what I did: https://github.com/hackforla/ohana-web-search-la/commit/8d6a35436be4d95714fc92fac4abfa6b43c69b70

cf. https://github.com/jwhitley/requirejs-rails/issues/221

**Comment by pmackay** [comment]
@md5 thanks a lot for responding, fixed it! :)

**Comment by md5** [comment]
It might be good to leave this issue open until a versioned release of the
requirejs-rails gem with the fix is created.

**Comment by anselmbradford** [comment]
Thanks for the report. At some point I'll look into transitioning this project to browserify or webpack to follow the evolution of front-end module loaders.
