### ISSUE TITLE
Mandrill becoming a paid add-on for MailChimp

### ISSUE THREAD

**Issue by md5** [codeforamerica/ohana-web-search#827]
I'm opening this issue to discuss moving away from the Mandrill add-on for Heroku. Mandrill is becoming a paid add-on for MailChimp as detailed in this blog post: http://blog.mailchimp.com/important-changes-to-mandrill/

From what I can tell, the cost for Mandrill will now be $20/month for the lowest price point. As this comes out to $480/year, I think this is clearly beyond the budget of most Ohana installations.

**Comment by monfresh** [comment]
Yep. Feel free to submit a PR that replaces Mandrill with Sengrid, which still has a free plan as of today.
